spring.application.name=watches_final

server.port=9002

spring.datasource.url=jdbc:mysql://localhost:3306/watches_final
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

secret=ajwkdi21jrnuj234rnur2i3hro23nfjn2jnfj32r9832yhuruye9fh92
